### ISSUE TITLE
Broken validation function

### ISSUE THREAD

**Issue by sebastiand** [Copperis/DropdownImageField#6]
The `validation()` function is broken, because `getSourceAsArray()` does not return an array with key => value pairs.

The validation checks if the selected value of the `$keyField` exists as key in the array that is returned by `getSourceAsArray()`.
But this function returns an array that has no keys (just indexes 0,1,2, etc.) and DataObjects assigned as value.

**Example**
We select an item with ID 5, but only have 2 items to select.
Then the `getSourceAsArray()` will return array(DataObject1, Dataobject2).
A check for the ID 5 in this array will return false, so the validation will not be passed.

**Solution**
We need to rewrite the `getSourceAsArray()` function to return a proper key => value array from the source DataList, using the $keyField as key and $labelField as value.

**Comment by h7io** [comment]
Hi,

thanks for reporting and providing a fix. Merged.
